支持过场动画渲染
dontpanic92/OpenPAL3 pull request #18
Opened 2022-01-08 17:03 UTC by chrox

* 更新到`ash-0.35`和`imgui-rs-vulkan-renderer-1.1`；
* 修复调整窗口大小会导致`imgui renderer`销毁重建的问题；
* 音视频流统一使用`MediaEngine`创建；
* 使用`ffmpeg`解码Bink视频，并通过`imgui renderer`渲染到GUI层。

P.S. 为了支持Android和iOS，OpenAL音频输出后端可以迁移到`cpal`。

2022-01-08 19:09 UTC, dontpanic92 commented
👍👍

还没详细看 code changes，但是有几个问题需要首先讨论一下：

一是 ffmpeg 是 LGPL Licensed，Radiance 是 MIT Licensed，所以在 radiance 里直接 `features=['build']` 静态链接是不行的。另外为了 bink 带一个 ffmpeg，总觉得有些太重了😂 这个问题可以这样解决：
- radiance 不直接依赖 ffmpeg，而让 opengb 来依赖。opengb/openpal3 是 GPLv3 Licensed，直接静态链接 ffmpeg 也没问题
- ffmpeg 的依赖最好是可以做成 optional feature
- 这一步可以以后再说：Bink 有一些开源的解码器实现 (c++ 居多，go 也有），大多也是 GPL 协议的。可以照着翻译成一个 rust crate，这样也就不需要 ffmpeg 了

二是 cpal 并不是 openal 的替代产品，openal 是带有 3d 音效混音功能的，cpal 只是单纯的音频输出抽象。Android 上支持的一种 3d 音效库是 OpenSL ES，可以在 radiance 里实现为一个新后端。

三是关于新添加的 `VideoSource` 和 `MediaEngine`：
- Audio 的特别之处在于，`AudioEngine` 需要承担混音以及音频输出的功能。从这一点上讲，`AudioEngine` 是与 `RenderingEngine` 并列的组件，只不过一个处理的是音频，一个处理的是画面（视频）。一个 `AudioSource` 就像一个 `RenderingComponent`。
- 所以我的看法是目前实现的 `VideoSource` 并不是与 `AudioSource` 并列的组件，一起放进一个 Media 的概念下组合成一个 `MediaEngine` 也不是很合适。事实上现在的 `VideoSource` 做的事更像是一个 VideoDecoder。或者也可以把它实现为类似 Unity 中的 [Movie Texture](https://docs.unity3d.com/Manual/class-MovieTexture.html)
- 另外就是 FFMpeg 是一个 Decoder，从设计上来说应该属于一个非常独立的部分。所以我觉得更好的方法是把 ffmpeg decoder 作为 `VideoSource` 的成员（aka. 组合），而不是 `VideoSource` 的一种实现。

具体的代码还没有看，我有时间再详细看一下。上面的几个问题还是挺重要的，有什么想法我们可以讨论一下

2022-01-09 08:58 UTC, chrox commented
嗯，这几个问题确实比较重要。
1. 之前没有注意到到许可协议不兼容，可以使用动态链接的ffmpeg，或者采用其他兼容协议的bink解码器；
2. 看目前的代码没有用到OpenAL的3D音效，所以才想到替换为cpal，如果后续有这样的需求规划那还是保留着；
3. 同意把`VideoSource`放到`RenderingEngine`下面。

2022-01-10 13:19 UTC, chrox commented
Windows系统的CI貌似挂掉了。

2022-01-12 11:50 UTC, dontpanic92 requested changes

2022-01-12 11:50 UTC, dontpanic92 commented on radiance/src/rendering/vulkan/descriptor_managers.rs
> +        let descriptor_pool = Self::create_descriptor_pool(&self.device).unwrap();
`descriptor_pool` 应该需要调用 `device.destroy_descriptor_pool` 释放

2022-01-12 11:50 UTC, dontpanic92 commented on radiance/src/rendering/vulkan/descriptor_managers.rs
> +        Ok(set)
`descriptor_set` 也需要调用 `device.free_descriptor_sets` 释放，这个有在哪做处理吗？

2022-01-12 11:50 UTC, dontpanic92 commented on radiance/src/rendering/vulkan/imgui.rs
> +            if cfg!(target_os = "macos") {
这个看起来可以适用于所有系统？

2022-01-12 11:50 UTC, dontpanic92 commented on radiance/src/rendering/vulkan/texture.rs
> +        image.copy_from(&buffer, 0, &command_runner)?;
从 L41 开始似乎跟 `from_buffer` 是一致的，可以考虑直接调用 `from_buffer`

2022-01-12 11:51 UTC, dontpanic92 commented
> Windows系统的CI貌似挂掉了。

好像那几天 chocolatey 出了问题，现在似乎好了

2022-01-12 13:22 UTC, chrox commented on radiance/src/rendering/vulkan/imgui.rs
> +            if cfg!(target_os = "macos") {
是的，我在移植到android系统的时候发现，android也需要这个fix。

2022-01-12 15:30 UTC, chrox commented on radiance/src/rendering/vulkan/descriptor_managers.rs
> +        Ok(set)
done

2022-01-12 15:31 UTC, chrox commented on radiance/src/rendering/vulkan/descriptor_managers.rs
> +        let descriptor_pool = Self::create_descriptor_pool(&self.device).unwrap();
done

2022-01-13 04:43 UTC, chrox commented on radiance/src/rendering/vulkan/factory.rs
> +            .free_texture_descriptor_set(descriptor_set);
跑起来没问题，但是确实有一堆validation error需要处理。

2022-01-13 08:08 UTC, chrox commented on radiance/src/rendering/vulkan/factory.rs
> +            .free_texture_descriptor_set(descriptor_set);
已处理完所有validation error。

2022-01-13 08:18 UTC, dontpanic92 approved these changes

2022-01-13 08:19 UTC, merged

2022-01-13 08:20 UTC, dontpanic92 commented
🚀